#!/bin/bash
print="False"
showHelp() {
    cat <<EOF
        Usage $0 [OPTION]...


        OPTIONS:
        -f --file OPTION            File to load
        -p, --print                 Print File Contents
        -h, --help                  Show help
EOF
}
while [[ $# -gt 0 ]]; do
    case "${1}" in
    -f | --file)
        shift
        file=$1
        shift
        ;;
    -p | --print)
        shift
        print="True"
        shift
        ;;
    -h | --help)
        showHelp
        exit 0
        ;;
    *)
        echo -e "ERROR: Unrecognized option '${1}'."
        echo "Try $0 --help for more information"
        exit 1
        ;;
    esac
done
if [ $print == "True" ]; then
    cat $file
    echo
fi
if test -f "$file"; then
    source $file &> !error
    if test -f "!error"; then
    echo -ne "The loaded file does not seem to contain a bash script or it contains errors\n\n"
    rm !error
    fi
    echo "$file loaded"
else
    echo "$file does not exist"
fi
unset file
unset print